# Generated by Django 2.2.4 on 2019-08-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(db_index=True, max_length=100, verbose_name='Модель')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('op_system', models.CharField(max_length=50, verbose_name='Операционная система')),
                ('ram', models.PositiveIntegerField(verbose_name='Оперативная память')),
                ('dpi', models.PositiveIntegerField(verbose_name='Число пикселей на дюйм')),
                ('double_cam', models.BooleanField(verbose_name='двойная камера')),
                ('cpu', models.CharField(max_length=150, verbose_name='Процессор')),
                ('resolution', models.CharField(max_length=50, verbose_name='Разрешение экрана')),
                ('fm_radio', models.BooleanField(verbose_name='FM-Радио')),
                ('additionally', models.TextField(verbose_name='Дополнительно')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
