# Generated by Django 2.2.4 on 2019-08-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('price', models.PositiveIntegerField(blank=True)),
                ('image', models.ImageField(upload_to='')),
                ('release_date', models.DateField(blank=True)),
                ('lte_exists', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
    ]
