# Generated by Django 2.2.4 on 2019-08-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(default=models.CharField(db_index=True, max_length=150), max_length=150, unique=True),
        ),
    ]
